# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routine_error_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorMessage(object):
    def setupUi(self, ErrorMessage):
        ErrorMessage.setObjectName("ErrorMessage")
        ErrorMessage.resize(400, 176)
        ErrorMessage.setMinimumSize(QtCore.QSize(400, 176))
        ErrorMessage.setMaximumSize(QtCore.QSize(400, 176))
        self.button_ok = QtWidgets.QPushButton(ErrorMessage)
        self.button_ok.setGeometry(QtCore.QRect(150, 140, 89, 25))
        self.button_ok.setObjectName("button_ok")
        self.textBrowser = QtWidgets.QTextBrowser(ErrorMessage)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 381, 121))
        self.textBrowser.setStyleSheet("background-color: rgba(253, 252, 252, 0);")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(ErrorMessage)
        QtCore.QMetaObject.connectSlotsByName(ErrorMessage)

    def retranslateUi(self, ErrorMessage):
        _translate = QtCore.QCoreApplication.translate
        ErrorMessage.setWindowTitle(_translate("ErrorMessage", "Dialog"))
        self.button_ok.setText(_translate("ErrorMessage", "Ok"))
